---
- name: Copy firewall script
  copy:
    src: firewall.sh
    dest: /usr/local/sbin/firewall.sh
    owner: root
    group: root
    mode: u=rwx,g=r,o=r

# this deb install utilities to applay firewall rules at boot 
- name: Install iptables-persitent
  apt:
    name: iptables-persistent
    state: latest

# this command is needed to initialize the system
- name: applay common firewall rules
  command: "/usr/local/sbin/firewall.sh"
  notify: run_iptables_save
  when: applay_common_firewall

- name: Copy SSH server conf
  copy:
    src: firewall.sh
    dest: /usr/local/sbin/firewall.sh
    owner: root
    group: root
    mode: u=rwx,g=r,o=r
  notify: restart_sshserver


 # setup stuff to backaup using rsnapshot
- name: create snapshot group
  ansible.builtin.group:
    name: snapshot
    state: present
    system: true

- name: create snapshot user
  ansible.builtin.user:
    name: snapshot
    groups: snapshot
    state: present
    system: true

- name: Install rsync
  apt:
    name: rsync
    state: latest


